ypl.app:
  jwtSecret: yplSecretKey
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 86400000
  limitOfTokensPerUser: 5

  confirmTokenLink: http://localhost:8080/api/v1/registration/confirm?token=
  confirmTokenExpirationMs: 900000

  senderEmailAddress: simplyblog@admin.com

spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 20
  datasource:
    url: jdbc:postgresql://localhost:5432/simplyblog_db
    username: postgres
    password: password

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  # Jackson Serialization Issue Resolver
  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

logging:
  level:
    root: WARN
    com.github.ypl.simplyblog: INFO

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true